name: projeto_final_flutter
description: "Projeto Final Flutter - Lince Tech Academy 2025"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  flutter_localization: ^0.3.3
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  path: ^1.9.1
  font_awesome_flutter: ^10.8.0
  geolocator: ^14.0.2
  google_maps_flutter: ^2.12.3
  firebase_auth: ^5.6.2
  firebase_core: ^3.15.1
  http: ^1.4.0
  flutter_polyline_points: ^3.0.1
  collection: ^1.19.1
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  flutter_dotenv: ^5.2.1
  flutter_rating: ^2.0.2
  uuid: ^4.5.1
  google_fonts: ^6.3.0
  go_router: ^16.2.0
  flutter_native_splash: ^2.4.6
  extended_masked_text: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - 'assets/images/default_profile_picture.png'
    - .env

flutter_native_splash:
  color: "#F54927"
  android: true
  ios: true
